- name: install Catalogue component
  hosts: Catalogue
  become: yes
  tasks:
  - name: install Catalogue
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

  - name: installing nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed

  - name: Add the user roboshop
    ansible.builtin.user:
      name: roboshop

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Unarchive a file that needs to be downloaded 
    ansible.builtin.unarchive:
      src: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /app
      remote_src: yes

  - name: installing npm
    ansible.builtin.shell: npm install 

  - name: Copy file 
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: Restart catalogue.service
    ansible.builtin.systemd_service:
      state: restarted
      daemon_reload: true

  - name: enabled and start catalogue
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes

  - name: Copy file 
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: installing mongodb-org-shell
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed

  - name: connecting to mongo schema
    ansible.builtin.shell: mongo --host 172.31.89.145 </app/schema/catalogue.js

  - name: enabled and start catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      


        
      


    

    
